### PR TITLE
✨ feat(commitlint): add commitlint and husky hook

### PR DESCRIPTION
**Pull request by hedenica**

### CODE REVIEW

**Comment by hedenica** [comment]
@fdaciuk  👀

**Comment by fdaciuk** [comment]
Hey @hedenica! Sorry, I'll check that out soon :D

**Comment by fdaciuk** [comment]
Hey @hedenica! It works like a charm on Linux, but Windows cried a bit xD
When you try to use this on Windows (Powershell terminal), every pressed key will print all the content again:



That shit happens with every option on the `cz` CLI:



Do you want to try find something about this issue? Because if this is a no solutionable problem, I think we can change the approach: instead of using `cz` directly with Husky, we can use this command as an NPM Script (`yarn commit` or something).

What do you think?

**Comment by hedenica** [comment]
Heey! Sorry for the delay 😄  
I'll take a look at this as soon as I can, but I do think that we're gonna have to change the command.

**Comment by fdaciuk** [comment]
No problem! :D 
It's ok for me to create a new command :)

**Pull request closed without merging**
