### PR TITLE
add vite-plugin-svgr

### PR DESCRIPTION
**Pull request by gabepinheiro**
- Add `vite-plugin-svgr` to import svg's as `ReactComponent`

### CODE REVIEW

**Comment by gabepinheiro** [comment]
@fdaciuk xD.

**Comment by fdaciuk** [comment]
Hey @gabepinheiro! Thanks for your contribution! :D 

To make this code works properly with Jest, you have to make some additional configurations:

At `jest.config.ts`:
- Remove `svg` from `assetsKey` variable;
- Add this line to `moduleNameMapper` entry: `'\\.svg$': '<rootDir>/src/config/tests/mocks/svg.ts',`;
- Add this line to `transform` entry: `'\\.svg$': 'ts-jest',`.

At `tsconfig.json`, you can just remove the commented line on `typeRoots` ;)

**Comment by gabepinheiro** [comment]
Hey @fdaciuk! Thanks for the comment and the additional settings. I took advantage and also includes a new configuration

At jest.config.ts includes `coveragePathIgnorePatterns`:

```
coveragePathIgnorePatterns: [
   '/node_modules/',
   'config/tests',
 ],
```

**Comment by fdaciuk** [comment]
Great work @gabepinheiro! Thanks 👏🏾 👏🏾

**Pull request merged**
